version: 2

models:
  - name: activation_gbp_data
    config:
      tags: ["4_hourly"]
    description: "A transformation that creates the list of user for a campaign"
    columns:
      - name: user_id
        description: "Unique Identifier of the user"
  - name: activation_ghs_data
    config:
      tags: ["4_hourly"]
    description: "A transformation that creates the list of user for a campaign"
    columns:
      - name: user_id
        description: "Unique Identifier of the user"
  - name: activation_kes_data
    config:
      tags: ["4_hourly"]
    description: "A transformation that creates the list of user for a campaign"
    columns:
      - name: user_id
        description: "Unique Identifier of the user"
  - name: activation_ngn_data
    config:
      tags: ["4_hourly"]
    description: "A transformation that creates the list of user for a campaign"
    columns:
      - name: user_id
        description: "Unique Identifier of the user"
  - name: activation_rwf_data
    config:
      tags: ["4_hourly"]
    description: "A transformation that creates the list of user for a campaign"
    columns:
      - name: user_id
        description: "Unique Identifier of the user"
  - name: activation_tzs_data
    config:
      tags: ["4_hourly"]
    description: "A transformation that creates the list of user for a campaign"
    columns:
      - name: user_id
        description: "Unique Identifier of the user"
  - name: activation_ugx_data
    config:
      tags: ["4_hourly"]
    description: "A transformation that creates the list of user for a campaign"
    columns:
      - name: user_id
        description: "Unique Identifier of the user"
  - name: activation_usd_data
    config:
      tags: ["4_hourly"]
    description: "A transformation that creates the list of user for a campaign"
    columns:
      - name: user_id
        description: "Unique Identifier of the user"
  - name: activation_zar_data
    config:
      tags: ["4_hourly"]
    description: "A transformation that creates the list of user for a campaign"
    columns:
      - name: user_id
        description: "Unique Identifier of the user"
  - name: activation_zmw_data
    config:
      tags: ["4_hourly"]
    description: "A transformation that creates the list of user for a campaign"
    columns:
      - name: user_id
        description: "Unique Identifier of the user"
