WITH filter_users AS
(
	SELECT
		uos.ONBOARDING_TIME ,
		uos.ONBOARDING_NUM_IP,
		uos.ONBOARDING_USER_PER_IP_COUNT
	FROM
		CHIPPER.UTILS.USER_ONBOARDING_SCORE uos
		LEFT JOIN CHIPPER.{{var("core_public")}}.USERS u
			ON uos.USER_ID = u.ID
	WHERE
		u.CREATED_AT >= DATEADD(DAY, -7, CURRENT_DATE())
)
SELECT * FROM filter_users
