version: 2

models:
  - name: upsell_new_user_offer_ghs
    config:
      tags: ["4_hourly"]
    description: "A model for upsell offers for new users who completed their first campaign offer in GHS"
  - name: upsell_new_user_offer_ngn
    config:
      tags: ["4_hourly"]
    description: "A model for upsell offers for new users who completed their first campaign offer in NGN"
  - name: upsell_new_user_offer_tzs
    config:
      tags: ["4_hourly"]
    description: "A model for upsell offers for new users who completed their first campaign offer in TZS"
  - name: upsell_new_user_offer_usd
    config:
      tags: ["4_hourly"]
    description: "A model for upsell offers for new users who completed their first campaign offer in USD"
  - name: upsell_new_user_offer_zmw
    config:
      tags: ["4_hourly"]
    description: "A model for upsell offers for new users who completed their first campaign offer in ZMW"
  - name: upsell_new_user_offer_kes
    config:
      tags: ["4_hourly"]
    description: "A model for upsell offers for new users who completed their first campaign offer in KES"
  - name: upsell_new_user_offer_rwf
    config:
      tags: ["4_hourly"]
    description: "A model for upsell offers for new users who completed their first campaign offer in RWF"
  - name: upsell_new_user_offer_ugx
    config:
      tags: ["4_hourly"]
    description: "A model for upsell offers for new users who completed their first campaign offer in UGX"
  - name: upsell_new_user_offer_zar
    config:
      tags: ["4_hourly"]
    description: "A model for upsell offers for new users who completed their first campaign offer in ZAR"
