WITH small_transaction_details AS (
    SELECT
        DISTINCT transfer_id,
        transaction_details,
        shortened_transaction_details,
        outgoing_user_transfer_metadata_details,
        incoming_user_transfer_metadata_details,
        COALESCE(transaction_details:"_internalTransactionDetails":"paymentMethodDetails":"isExternal",false) AS is_external
    FROM {{ ref('transaction_details') }}
)
SELECT 
    DISTINCT expanded_ledgers.transfer_id,
    expanded_ledgers.journal_id,
    expanded_ledgers.journal_type,
    expanded_ledgers.transfer_type,
    expanded_ledgers.ledger_entry_id,
    expanded_ledgers.hlo_id,
    expanded_ledgers.ledger_currency,
    expanded_ledgers.ledger_amount,
    expanded_ledgers.ledger_amount_in_usd,
    expanded_ledgers.hlo_status,
    expanded_ledgers.corridor,
    expanded_ledgers.hlo_created_at AS created_at,
    expanded_ledgers.hlo_updated_at AS updated_at,
    small_transaction_details.shortened_transaction_details::text AS short_transaction_details,
    expanded_ledgers.main_party_user_id AS user_id,
    eu_main_party.display_first_name AS display_first_name,
    eu_main_party.display_last_name AS display_last_name,
    eu_main_party.legal_first_name AS legal_first_name,
    eu_main_party.legal_last_name AS legal_last_name,
    eu_main_party.tag AS user_tag,
    eu_main_party.primary_currency AS primary_currency,
    eu_main_party.acquisition_source AS acquisition_source,
    eu_main_party.created_at AS user_created_at,
    eu_main_party.kyc_tier AS user_kyc_tier,
    small_transaction_details.OUTGOING_USER_TRANSFER_METADATA_DETAILS:"transferMetadataDetails"[0]:"ipAddress" AS ip_address,
    small_transaction_details.OUTGOING_USER_TRANSFER_METADATA_DETAILS:"transferMetadataDetails"[0]:"deviceId" AS chipper_device_id,
    expanded_ledgers.counter_party_user_id AS other_party_user_id,
    eu_counter_party.display_first_name AS other_party_display_first_name,
    eu_counter_party.display_last_name AS other_party_display_last_name,
    eu_counter_party.legal_first_name AS other_party_legal_first_name,
    eu_counter_party.legal_last_name AS other_party_legal_last_name,
    eu_counter_party.tag AS other_party_tag,
    eu_counter_party.primary_currency AS other_party_primary_currency,
    eu_counter_party.acquisition_source AS other_party_acquisition_source,
    eu_counter_party.created_at AS other_party_user_created_at,
    eu_counter_party.kyc_tier AS other_party_user_kyc_tier,
    small_transaction_details.INCOMING_USER_TRANSFER_METADATA_DETAILS:"transferMetadataDetails"[0]:"deviceId" AS other_party_chipper_device_id,
    small_transaction_details.INCOMING_USER_TRANSFER_METADATA_DETAILS:"transferMetadataDetails"[0]:"ipAddress" AS other_party_ip_address,    
    small_transaction_details.OUTGOING_USER_TRANSFER_METADATA_DETAILS:"transferMetadataDetails"[0]:"countryCode" AS country_code,
    small_transaction_details.OUTGOING_USER_TRANSFER_METADATA_DETAILS:"transferMetadataDetails"[0]:"city" AS city,
    small_transaction_details.OUTGOING_USER_TRANSFER_METADATA_DETAILS:"transferMetadataDetails"[0]:"region" AS region,
    small_transaction_details.OUTGOING_USER_TRANSFER_METADATA_DETAILS:"transferMetadataDetails"[0]:"connectionType" AS connection_type,
    small_transaction_details.INCOMING_USER_TRANSFER_METADATA_DETAILS:"transferMetadataDetails"[0]:"countryCode" AS other_party_country_code,
    small_transaction_details.INCOMING_USER_TRANSFER_METADATA_DETAILS:"transferMetadataDetails"[0]:"city" AS other_party_city,
    small_transaction_details.INCOMING_USER_TRANSFER_METADATA_DETAILS:"transferMetadataDetails"[0]:"region" AS other_party_region,
    small_transaction_details.INCOMING_USER_TRANSFER_METADATA_DETAILS:"transferMetadataDetails"[0]:"connectionType" AS other_party_connection_type,
    small_transaction_details.is_external,
    small_transaction_details.TRANSACTION_DETAILS AS TRANSACTION_DETAILS_EXTENDED,
    expanded_ledgers.is_original_transfer_reversed,
    expanded_ledgers.is_transfer_reversal
FROM {{ ref('expanded_ledgers') }}
LEFT JOIN {{ ref('expanded_users') }} AS EU_MAIN_PARTY ON expanded_ledgers.main_party_user_id = EU_MAIN_PARTY.user_id
LEFT JOIN {{ ref('expanded_users') }} AS EU_COUNTER_PARTY ON expanded_ledgers.counter_party_user_id = EU_COUNTER_PARTY.user_id
LEFT JOIN small_transaction_details ON expanded_ledgers.transfer_id = small_transaction_details.transfer_id
