version: 2

models:
  - name: reactivation_gbp_data
    config:
      tags: ["4_hourly"]
    description: "A transformation that creates the list of user for a campaign"
    columns:
      - name: user_id
        description: "Unique Identifier of the user"
  - name: reactivation_ghs_data
    config:
      tags: ["4_hourly"]
    description: "A transformation that creates the list of user for a campaign"
    columns:
      - name: user_id
        description: "Unique Identifier of the user"
  - name: reactivation_kes_data
    config:
      tags: ["4_hourly"]
    description: "A transformation that creates the list of user for a campaign"
    columns:
      - name: user_id
        description: "Unique Identifier of the user"
  - name: reactivation_ngn_data
    config:
      tags: ["4_hourly"]
    description: "A transformation that creates the list of user for a campaign"
    columns:
      - name: user_id
        description: "Unique Identifier of the user"
  - name: reactivation_rwf_data
    config:
      tags: ["4_hourly"]
    description: "A transformation that creates the list of user for a campaign"
    columns:
      - name: user_id
        description: "Unique Identifier of the user"
  - name: reactivation_tzs_data
    config:
      tags: ["4_hourly"]
    description: "A transformation that creates the list of user for a campaign"
    columns:
      - name: user_id
        description: "Unique Identifier of the user"
  - name: reactivation_ugx_data
    config:
      tags: ["4_hourly"]
    description: "A transformation that creates the list of user for a campaign"
    columns:
      - name: user_id
        description: "Unique Identifier of the user"
  - name: reactivation_usd_data
    config:
      tags: ["4_hourly"]
    description: "A transformation that creates the list of user for a campaign"
    columns:
      - name: user_id
        description: "Unique Identifier of the user"
  - name: reactivation_zar_data
    config:
      tags: ["4_hourly"]
    description: "A transformation that creates the list of user for a campaign"
    columns:
      - name: user_id
        description: "Unique Identifier of the user"
  - name: reactivation_zmw_data
    config:
      tags: ["4_hourly"]
    description: "A transformation that creates the list of user for a campaign"
    columns:
      - name: user_id
        description: "Unique Identifier of the user"
