version: 2

models:
  - name: reactivation_gbp_stock
    config:
      tags: ["4_hourly"]
    description: "A transformation that creates the list of user for a campaign"
    columns:
      - name: user_id
        description: "Unique Identifier of the user"
  - name: reactivation_ghs_stock
    config:
      tags: ["4_hourly"]
    description: "A transformation that creates the list of user for a campaign"
    columns:
      - name: user_id
        description: "Unique Identifier of the user"
  - name: reactivation_kes_stock
    config:
      tags: ["4_hourly"]
    description: "A transformation that creates the list of user for a campaign"
    columns:
      - name: user_id
        description: "Unique Identifier of the user"
  - name: reactivation_ngn_stock
    config:
      tags: ["4_hourly"]
    description: "A transformation that creates the list of user for a campaign"
    columns:
      - name: user_id
        description: "Unique Identifier of the user"
  - name: reactivation_rwf_stock
    config:
      tags: ["4_hourly"]
    description: "A transformation that creates the list of user for a campaign"
    columns:
      - name: user_id
        description: "Unique Identifier of the user"
  - name: reactivation_tzs_stock
    config:
      tags: ["4_hourly"]
    description: "A transformation that creates the list of user for a campaign"
    columns:
      - name: user_id
        description: "Unique Identifier of the user"
  - name: reactivation_ugx_stock
    config:
      tags: ["4_hourly"]
    description: "A transformation that creates the list of user for a campaign"
    columns:
      - name: user_id
        description: "Unique Identifier of the user"
  - name: reactivation_usd_stock
    config:
      tags: ["4_hourly"]
    description: "A transformation that creates the list of user for a campaign"
    columns:
      - name: user_id
        description: "Unique Identifier of the user"
  - name: reactivation_zar_stock
    config:
      tags: ["4_hourly"]
    description: "A transformation that creates the list of user for a campaign"
    columns:
      - name: user_id
        description: "Unique Identifier of the user"
  - name: reactivation_zmw_stock
    config:
      tags: ["4_hourly"]
    description: "A transformation that creates the list of user for a campaign"
    columns:
      - name: user_id
        description: "Unique Identifier of the user"
