{% set category_dictionary= {
  'Cards - Incoming Transaction': 'ChipperCommon',
  'KYC - Decision Accepted': 'ChipperCommon',
  'KYC - Decision Rejected': 'ChipperCommon',
  'Ledger Activity': 'ChipperCommon',
  'LIVENESS - Decision Rejected': 'ChipperCommon',
  'VERIFICATION_KYC_PROOF_OF_ADDRESS': 'KYC',
  'CARDS_MORE_INFO_TAPPED': 'Misc Tapped',
  'FACETEC_SDK_SCREEN_ClOSED': 'Misc Tech',
  'Privacy - Hide Balance': 'Misc User',
  'REFERRALS_CLOSE_INPUT_SCREEN': 'Referrals',
  'REFERRALS_SHARE_TAPPED': 'Referrals',
  'Add Auth%': 'Add Auth',
  'Add Card%': 'Add Card',
  'Address Input%': 'Address Input',
  'Airtime%': 'Airtime',
  'Bills%': 'Bills',
  'Biometric Lock%': 'Misc Tech',
  'Biometric%': 'Biometric',
  '%Branch%': 'Branch',
  'Cards%': 'Cards',
  'Crypto%': 'Crypto',
  'Data Bundle%': 'Data Bundle',
  'Experiment%': 'Experiments',
  'Feature Status%': 'Feature Status',
  'Feed%': 'Feed',
  'Forgot PIN%': 'Forgot PIN',
  'KYC%': 'KYC',
  'Linked Accounts%': 'Linked Accounts',
  'Merchant Authorisations%': 'Merchant Authorisations',
  'Pay %': 'Pay',
  'Profile%': 'Profile',
  'Payment%': 'Payment Methods',
  'Pass Through%': 'Pass Through',
  'Rados%': 'Rados',
  'Referrals%': 'Referrals',
  'Request%': 'Request',
  'Share Tag%': 'Share Tag',
  'S2NC%': 'S2NC',
  'Stocks%': 'Stocks',
  '%Onboarding%': 'Onboarding', 
  'Account Creation - Started': 'Onboarding',
  '%OTP%': 'Add Auth',
  'Bank%': 'Misc Financial',
  'BVN%': 'Misc Financial',
  'Nuban%': 'Misc Financial',
  'Paystack%': 'Misc Financial',
  'QR%': 'Misc Tech',
  'Sign %': 'Misc Tech',
  'Token%': 'Misc Tech',
  'Pin%': 'Misc Tech',
  'Facetec%': 'Misc Tech',
  'Security Lock - Changed': 'Misc Tech',
  'Device - Storage': 'Misc Tech',
  'User %': 'Misc User',
  'Tag%': 'Misc User',
  'Proof of Address%': 'Misc User',
  'Deposit%': 'Transactions', 
  'Withdrawal%': 'Transactions',
  '%Viewed': 'Misc Viewed',
  '%Tapped%': 'Misc Tapped'}
 %}

SELECT 
  TRUNC(event_time, 'hour') AS event_time,
  primary_currency,
  CASE {% for key, value in category_dictionary.items() %}
    WHEN event_type LIKE '{{key}}' THEN '{{value}}' {% endfor %} ELSE 'Other'
  END AS event_category,
  event_type, 
  version_name,
  COUNT(*) AS event_count
FROM CHIPPER.AMPLITUDE.EVENTS_204512 events
JOIN
  CHIPPER.{{var("core_public")}}.USERS users ON users.id = events.user_id  
{{ dbt_utils.group_by(n=5) }}
